#this is for chess

#main:main.c    			两种模式等效
#	gcc main.c -o main -Wall
#clean:
#	rm -rf main
#	rm -rf *.o
#	rm -rf ~*

src=main.c i_dta.c basic_shapes.c			###加入新的函数直接跟在后边即可，之间用空格隔开
para=-o main -Wall
main:$(src)
	gcc $(src) $(para)
clean:
	rm -rf main
	rm -rf *.o
	rm -rf ~*
        
        
